#!/bin/bash

# Utility script for defragmenting all tables in the local MySQL database
# maintained by Plesk.
#
# WARNING: Do not run this on large production servers.
#          This script is only intended for small-scale deployments.
#
# @author Guy Paddock (guy.paddock@redbottledesign.com)

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2;
   exit 1;
fi;

# Print a timestamp, for logging purposes.
date;


mysqlcheck -uadmin -p`cat /etc/psa/.psa.shadow` --auto-repair --optimize --all-databases;
